# Generated by Django 2.2.16 on 2022-03-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220314_2008'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='uniqe_follow',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_followers'),
        ),
    ]
